// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxC5q8y3xr1KyhD_lRZQm3TTEmLBPXwCY',
    appId: '1:497377730403:web:da06557c3eb8ccb98f7d56',
    messagingSenderId: '497377730403',
    projectId: 'hotpot-611a8',
    authDomain: 'hotpot-611a8.firebaseapp.com',
    storageBucket: 'hotpot-611a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKkAKvKBkl-oPodAjXRZKoRZ4Ckttkizw',
    appId: '1:276675541894:android:e6fae175b664e9711a8a07',
    messagingSenderId: '276675541894',
    projectId: 'flutter-ai-playground-28f5b',
    storageBucket: 'flutter-ai-playground-28f5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ymnYOb8z5s_PjzUtLxCtojCW02aOG2M',
    appId: '1:276675541894:ios:dd82cee8a8daa52f1a8a07',
    messagingSenderId: '276675541894',
    projectId: 'flutter-ai-playground-28f5b',
    storageBucket: 'flutter-ai-playground-28f5b.firebasestorage.app',
    iosBundleId: 'com.example.hotpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ymnYOb8z5s_PjzUtLxCtojCW02aOG2M',
    appId: '1:276675541894:ios:dd82cee8a8daa52f1a8a07',
    messagingSenderId: '276675541894',
    projectId: 'flutter-ai-playground-28f5b',
    storageBucket: 'flutter-ai-playground-28f5b.firebasestorage.app',
    iosBundleId: 'com.example.hotpot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP5ixrkfsuZbHQCk9FtwjTyEUAyUZol10',
    appId: '1:276675541894:web:68fbf8a8cd9367091a8a07',
    messagingSenderId: '276675541894',
    projectId: 'flutter-ai-playground-28f5b',
    authDomain: 'flutter-ai-playground-28f5b.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-28f5b.firebasestorage.app',
  );
}
